In [1]:
#1. Python program to add two Matrices

In [2]:
X = [[12,7,3],
    [4 ,5,6,7],
    [7 ,8,9]]
Y = [[5,8,1],
    [6,7,3,2],
    [4,5,9]]

In [3]:
result = [[X[i][j] + Y[i][j]  for j in range(len(X[i]))] for i in range(len(X))]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9, 9]
[11, 13, 18]


In [4]:
import numpy as np

A = np.array([[12, 7, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[5, 8, 1], [6, 7, 3], [4, 5, 9]])
C = A+B
print(C)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [40]:
#2. Python program to multiply two matrices

In [5]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]


result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
print(result)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


In [60]:
#3. Python program for Matrix Product

In [6]:
import numpy as np

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [63]:
#4. Adding and Subtracting Matrices in Python

In [7]:
import numpy as np
  
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print(np.add(A, B))

[[ 5  7]
 [ 9 11]]


In [8]:
import numpy as np
  
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Subtraction of two matrix")
print(np.subtract(B, A))

Subtraction of two matrix
[[3 3]
 [3 3]]


In [71]:
#5. Transpose a matrix in Single line in Python

In [9]:
A.T

array([[1, 3],
       [2, 4]])

In [86]:
#6. Python | Matrix creation of n*n

In [10]:
n=int(input("Enter a n for n*n matrix"))
import numpy as np  
a = np.random.randint(0, 100, (n, n))
a


Enter a n for n*n matrix6


array([[31,  0, 35, 30, 77, 42],
       [27, 98, 97, 95, 55, 48],
       [39, 21, 50, 16, 61, 21],
       [28,  7, 93, 86,  2, 20],
       [94, 17, 64, 36, 76, 68],
       [96,  2, 92, 35, 10, 98]])

In [ ]:
#7. Python | Get Kth Column of Matrix

In [11]:
n=int(input("Enter a n for  Kth Column of Matrix"))
a = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
k=n
c=[i[k] for i in a]
c

Enter a n for  Kth Column of Matrix2


[6, 10, 5]

In [4]:
#8. Python – Vertical Concatenation in Matrixa = np.array([[1, 2], [3, 4]])

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[2,2]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6, 2, 2])

In [15]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 2, 2]])

In [14]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [2, 2]])

In [15]:
#9. Python program to check if a string is palindrome or not

In [22]:
a=str(input("enter a word"))
if a==a[::-1]:
    print("word is a palindrome")
else:
    print("word is not a palindrome")   
    

enter a word
word is a palindrome


In [43]:
#10. Python program to check whether the string is Symmetrical or Palindrome

In [8]:
a=str(input("enter a word"))
b=a[0:int(len(a)/2)]
c=a[int(len(a)/2):]
if a==a[::-1]:
    print("word is a palindrome")
else:
    print("word is not a palindrome")
    
if  b==c:
    print("word is Symmetrical")
else:
     print("word is not  Symmetrical")   

enter a wordnoonnoon
word is a palindrome
word is Symmetrical
